//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPasswordApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int client_id { get; set; }
        public string forname { get; set; }
        public string lastname { get; set; }
        public string fathername { get; set; }
    }
}
