//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPasswordApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string user_id { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
    }
}
